import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type WebhookLogDocument = WebhookLog & Document;

@Schema({
  timestamps: true,
  collection: 'webhook_logs',
})
export class WebhookLog {
  @Prop({ required: true })
  webhook_id: string; // unique webhook identifier from provider or generated by us

  @Prop({ required: true })
  event_type: string; // e.g., "payment_status", "refund", etc.

  @Prop({ type: Object, required: true })
  payload: Record<string, any>; // raw payload from Edviron

  @Prop({ type: Object })
  headers: Record<string, any>; // request headers

  @Prop({
    required: true,
    enum: ['pending', 'processing', 'processed', 'failed', 'retrying'],
    default: 'pending',
  })
  status: string;

  @Prop()
  processed_at: Date;

  @Prop()
  error_message: string;

  @Prop({ default: 0 })
  retry_count: number;

  @Prop()
  next_retry_at: Date;

  @Prop()
  ip_address: string;

  @Prop()
  user_agent: string;

  @Prop({ type: Object })
  response: Record<string, any>; // our response back to provider (if any)

  @Prop()
  processing_time_ms: number;

  // ✅ Local reference to Order (internal ObjectId)
  @Prop({ type: Types.ObjectId, ref: 'Order' })
  related_order_id: Types.ObjectId;

  // ✅ Store Edviron’s collect_request_id (external)
  @Prop()
  provider_collect_id: string;

  // ✅ Store our internal custom_order_id (ORD_xxx)
  @Prop()
  custom_order_id: string;

  // ✅ Gateway raw status at webhook time
  @Prop()
  gateway_status: string;

  // ✅ Normalized status after mapping (success/pending/failed/cancelled)
  @Prop()
  normalized_status: string;
}

export const WebhookLogSchema = SchemaFactory.createForClass(WebhookLog);

// Indexes for fast lookups
WebhookLogSchema.index({ webhook_id: 1 });
WebhookLogSchema.index({ status: 1 });
WebhookLogSchema.index({ createdAt: -1 });
WebhookLogSchema.index({ event_type: 1 });
WebhookLogSchema.index({ related_order_id: 1 });
WebhookLogSchema.index({ provider_collect_id: 1 });
WebhookLogSchema.index({ custom_order_id: 1 });
